export const tasks = [{
        id: "1",
        text: "Buy milk",
        done: false,
        dateBegin: new Date(),
        dateFin: null,
    },
    {
        id: "2",
        text: "Pick up Tom from airport",
        done: false,
        dateBegin: new Date(),
        dateFin: null,
    },
    {
        id: "3",
        text: "Visit party",
        done: false,
        dateBegin: new Date(),
        dateFin: null,
    },
    {
        id: "4",
        text: "Visit doctor",
        done: true,
        dateBegin: new Date(),
        dateFin: null,
    },
    {
        id: "5",
        text: "Buy meat",
        done: true,
        dateBegin: new Date(),
        dateFin: null,
    },
];